<?php

declare(strict_types=1);

namespace App\User\Domain\Exceptions;

enum ErrorCode: string
{
    case USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
    case USER_INCORRECT_TOKEN = 'USER_INCORRECT_TOKEN';
    case MISSING_REQUIRED_NETWORK_NAME = 'MISSING_REQUIRED_NETWORK_NAME';
    case MISSING_REQUIRED_NETWORK_IDENTITY = 'MISSING_REQUIRED_NETWORK_IDENTITY';
    case NETWORK_ALREADY_ATTACHED = 'NETWORK_ALREADY_ATTACHED';
}
